[DEFAULT]
debian-branch = debian/latest
upstream-branch = main
# No tarballs to track (upstream uses git):
pristine-tar = False
pristine-tar-commit = False
git-ignore-new = True
# don't check if debian-branch == current branch:
ignore-branch = True

# Options only affecting gbp buildpackage
[buildpackage]
# Look for a tag matching the upstream version when creating a tarball
upstream-tree = e0b25b8764f5300e54b4833b0b63007f9fa18bf5
# Transparently handle submodules
submodules = True

# Options only affecting gbp import-orig
[import-orig]
# import filter:
filter = [ '.github', 'ci' ]

# Options only affecting gbp import-dsc
[import-dsc]
# set a different upstream branch:
#upstream-branch = svn-upstream
# import filter:
filter = [ '.github', 'ci' ]
#force committer to be the same as author
#author-is-committer = True
#same for the date
#author-date-is-committer-date = True

# Options only affecting gbp dch
[dch]
# Only include merge commits:
git-log = --merges
# Exclude merge commits:
#git-log = --no-merges
# Exclude upstream commits:
#git-log = --first-parent